name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploying to Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Write firebase credentials to json file
        run: echo "$firebase_credentials" > firebase-creds.json
        env:
          firebase_credentials: ${{ secrets.FIREBASE_CREDENTIALS }}

      - name: Create Procfile
        run: |
          echo -e "release: php artisan migrate\nweb: vendor/bin/heroku-php-apache2 ." > Procfile

      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP }}
          heroku_email: "bilalbentoumi@gmail.com"
